package model

enum class PrimaryChipsState {
    ICON_LEFT_DEFAULT, ICON_LEFT_PRESSED, ICON_LEFT_DISABLED,
    ICON_RIGHT_DEFAULT, ICON_RIGHT_PRESSED, ICON_RIGHT_DISABLED,
    DEFAULT, PRESSED, DISABLED
}